### PR TITLE
Fix small path bug in the Master implementation

### LINKED ISSUE #4: [Bug] bug in master.java
@fpj , I think there is a bug, and it should be the workerName, not the path in **getAbsentWorkerTasks(path)**

```
ChildrenCallback workerAssignmentCallback = new ChildrenCallback() {
        public void processResult(int rc, String path, Object ctx, List<String> children){
            switch (Code.get(rc)) { 
            case CONNECTIONLOSS:
                getAbsentWorkerTasks(path); // Here should be path.subString(path.lastIndexOf('/') + 1, path.length());
                break;
            case OK:
                LOG.info("Succesfully got a list of assignments: " 
                        + children.size() 
                        + " tasks");
                
                /*
                 * Reassign the tasks of the absent worker.  
                 */
                
                for(String task: children) {
                    getDataReassign(path + "/" + task, task);                    
                }
                break;
            default:
                LOG.error("getChildren failed",  KeeperException.create(Code.get(rc), path));
            }
        }
    };
```
https://github.com/fpj/zookeeper-book-example/blob/135b79b472fd2c45b82d78a3653532eecd69b6fe/src/main/java/org/apache/zookeeper/book/Master.java#L491

### PR DESCRIPTION
**Pull request by fpj**
As described in issue #4 , there is a bug in the call to `getAbsentWorkerTasks` in `workerAssignmentCallback`. This PR fixes the issue and adds a test case. The test case reproduces the problem and validates that the change fixes it.

Closes #4

### CODE REVIEW

File: src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java [hunk 1]
```diff
@@ -286,4 +289,57 @@ public void taskZooKeeperCrash() throws Exception {
...
+        LOG.info("Starting client");
+        Client c = new Client("localhost:" + port);
+        c.startZK();
+
+        while(!c.isConnected() &&
+                w.isConnected()){
+            Thread.sleep(100);
+        }
+
+        m.workerAssignmentCallback.processResult(Code.CONNECTIONLOSS.intValue(),
```
Comment (shivamka1) [inline src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: The test immediately ends without waiting for or asserting that the next line inside the callback is actually executed:
```java
getAbsentWorkerTasks(worker);
```

The test has to check what argument is passed to `getAbsentWorkerTasks`, so as to detect a regression.

To properly guard against this bug, we should override `getAbsentWorkerTasks()` in a test subclass to record its argument, then assert that it receives the worker name, not the full `/assign/<worker>` path. 

```java
class TestMaster extends Master {
    String lastWorker;
    @Override
    void getAbsentWorkerTasks(String worker) {
        lastWorker = worker;
    }
}
```

Then assert:
```java
assertEquals(workerName, m.lastWorker);
```

File: src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java [hunk 2]
```diff
@@ -286,4 +289,57 @@ public void taskZooKeeperCrash() throws Exception {
         w3.close();
         c.close();
     }
+
+    @Test(timeout=50000)
+    public void taskWorkerAssignmentCallback() throws Exception {
```
Comment (shivamka1) [inline src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: This test starts a full `Master`, `Worker`, and `Client`, connects all of them to ZooKeeper, waits for election, bootstraps znodes, registers the worker, etc. However, none of this is required for what the test is trying to validate.

The behaviour under test is purely local to:
```java
workerAssignmentCallback.processResult(...)
```

Specifically, we are testing that on `CONNECTIONLOSS`, the callback calls:
```java
getAbsentWorkerTasks(workerFromCtx);
```
instead of incorrectly passing the full path.

This behaviour does not depend on:
	•	whether Master is elected,
	•	whether Worker is registered,
	•	whether Client is connected,
	•	whether znodes exist in ZooKeeper,
	•	or any interaction with the actual ZooKeeper server.

The callback logic itself is a pure function of `(rc, path, ctx)`.

A much lighter test would:
	1.	Create a minimal `TestMaster` with a mocked or overridden `getAbsentWorkerTasks`.
	2.	Call the callback directly with synthetic parameters.
	3.	Assert the captured argument.

This removes network delays, timing flakiness, and unnecessary dependencies, making the test faster, clearer, and more stable.

**Review by shivamka1 — CHANGES_REQUESTED** [review]
Simpler test that truly detects any regression of this bug would look something like:
```java
@Test
public void workerAssignmentConnectionLossUsesWorkerNameNotFullPath() throws Exception {
    // Test double: capture the argument passed to getAbsentWorkerTasks
    class TestMaster extends Master {
        String lastWorkerArg;

        TestMaster(String hostPort) {
            super(hostPort);
        }

        @Override
        void getAbsentWorkerTasks(String worker) {
            this.lastWorkerArg = worker;
            // do NOT call super, we do not want real ZooKeeper interaction here
        }
    }

    TestMaster m = new TestMaster("localhost:" + port);

    String workerName = "worker-123";
    String path = "/assign/" + workerName;

    // Simulate a CONNECTIONLOSS on workerAssignmentCallback
    m.workerAssignmentCallback.processResult(
            Code.CONNECTIONLOSS.intValue(),
            path,
            workerName,     // ctx carries the worker name
            null
    );

    // This is the key assertion: with the bug present this will fail
    assertEquals(
            "getAbsentWorkerTasks must be called with worker name, not full path",
            workerName,
            m.lastWorkerArg
    );
}
```

File: src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java (hunk 2 above)
Comment (shivamka1) [reply src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: No need to wait for this long to test a simple function call that otherwise should take only a millisec or less.
```java
    @Test(timeout=50000)
```
If we had thousands of such tests, it would take forever to finish. Not ideal!

File: src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java [hunk 3]
```diff
@@ -286,4 +289,57 @@ public void taskZooKeeperCrash() throws Exception {
...
+         * Registers this worker so that the leader knows that
+         * it is here.
+         */
+        w.register();
+
+        LOG.info("Starting client");
+        Client c = new Client("localhost:" + port);
+        c.startZK();
+
+        while(!c.isConnected() &&
```
Comment (shivamka1) [inline src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: Not that this is relevant to this test but this condition seems wrong. The loop exits if either the **client connects**, or the **worker disconnects**, which makes the condition logically meaningless and couples two unrelated connection states. If the intention was to wait for both client and worker to connect before proceeding with the test, following logic makes more sense:
```java
while (!c.isConnected()) {
    Thread.sleep(100);
}

while (!w.isConnected()) {
    Thread.sleep(100);
}
```

Comment (shivamka1) [inline src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: A loop like this may never terminate.

File: src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java (hunk 1 above)
Comment (fpj) [reply src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: Those are fair comments, I was trying to keep the same structure that I followed back when I wrote these tests. I have re-written the test case as suggested, see if it works better for you now.

File: src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java [hunk 4]
```diff
@@ -286,4 +289,34 @@ public void taskZooKeeperCrash() throws Exception {
...
+        @Override
+        void getAbsentWorkerTasks(String worker) {
+            lastWorker = worker;
+        }
+    }
+
+    @Test
+    public void taskWorkerAssignmentCallback() throws Exception {
+        TestMaster m = new TestMaster();
+        m.startZK();
```
Comment (shivamka1) [inline src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: There is no need to start the zookeeper and close it in this test. 

In original code we do need zookeeper to get children like so:
```java
void getAbsentWorkerTasks(String worker){
        zk.getChildren("/assign/" + worker, false, workerAssignmentCallback, worker);
    }
```

This test already overrides the `getAbsentWorkerTasks`:
```java
 @Override
        void getAbsentWorkerTasks(String worker) {
            lastWorker = worker;
        }
```

Therefore starting and closing zk just adds noise and potential flakiness for a test that is purely about callback wiring.

**Review by shivamka1 — CHANGES_REQUESTED** [review]

File: src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java (hunk 4 above)
Comment (fpj) [reply src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: I did it because otherwise I was getting an error and I preferred to not touch other parts:

```
java.lang.NullPointerException: Cannot invoke "org.apache.zookeeper.server.ServerCnxnFactory.shutdown()" because "this.cnxnFactory" is null

	at org.apache.zookeeper.server.ZooKeeperServerMain.shutdown(ZooKeeperServerMain.java:132)
	at org.apache.zookeeper.book.StandaloneServer$TestZKSMain.shutdown(StandaloneServer.java:54)
	at org.apache.zookeeper.book.StandaloneServer.shutdown(StandaloneServer.java:105)
	at org.apache.zookeeper.book.BaseTestCase.tearDown(BaseTestCase.java:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
```

Comment (shivamka1) [reply src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: I see the `BaseTestCase` is trying to shut down the embedded zk server.
```java
public void tearDown(){
        this.zkServer.shutdown();
```

That explains the NPE! 

In a cleaner separation this would belong to a unit test suite without embedded ZK, but for this example test case your workaround makes sense.

**Comment by shivamka1** [comment]
LGTM

File: src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java (hunk 4 above)
Comment (fpj) [reply src/test/java/org/apache/zookeeper/book/TestTaskAssignment.java]: I have moved the test case to its own file now, this way we avoid the startZK and close calls. I think it is clean now, what do you think?

**Comment by shivamka1** [comment]
Perfect :)

File: src/test/java/org/apache/zookeeper/book/TestTaskWorkerAssignmentCallback.java [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+public class TestTaskWorkerAssignmentCallback {
+
+    @Test
+    public void taskWorkerAssignmentCallback() throws Exception {
+        TestMaster m = new TestMaster();
+        
+        String testWorker = "worker-001";
+        m.workerAssignmentCallback.processResult(KeeperException.Code.CONNECTIONLOSS.intValue(),
+                "/assign/" + testWorker,
+                (Object) testWorker,
```
Comment (shivamka1) [inline src/test/java/org/apache/zookeeper/book/TestTaskWorkerAssignmentCallback.java]: Just a nitpick! This casting is redundant. All Java classes implicitly extend `Object`.

File: src/test/java/org/apache/zookeeper/book/TestTaskWorkerAssignmentCallback.java [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+
+/**
+ * A test class for mocking the Master that records the last worker for which
+ * getAbsentWorkerTasks was called.
+ */
+class TestMaster extends Master {
+    String lastWorker;
+
+    TestMaster() {
+        super("localhost:2181");
```
Comment (shivamka1) [inline src/test/java/org/apache/zookeeper/book/TestTaskWorkerAssignmentCallback.java]: Another nitpick. I would have replaced: 
```java
super("localhost:2181");
```

with
```java
super("ignored");
```

just to highlight the irrelevance of connection string for this test and not mislead the reader. 

But otherwise its harmless!

**Review by shivamka1 — APPROVED** [review]
Looks perfect :)

File: src/test/java/org/apache/zookeeper/book/TestTaskWorkerAssignmentCallback.java (hunk 6 above)
Comment (fpj) [reply src/test/java/org/apache/zookeeper/book/TestTaskWorkerAssignmentCallback.java]: Done.

File: src/test/java/org/apache/zookeeper/book/TestTaskWorkerAssignmentCallback.java (hunk 5 above)
Comment (fpj) [reply src/test/java/org/apache/zookeeper/book/TestTaskWorkerAssignmentCallback.java]: Done
